### ISSUE TITLE
在 Android 6.0 上进入/退出 Activity 的动画失效

### ISSUE THREAD

**Issue by JC6** [ikew0ng/SwipeBackLayout#113]
使用 `<item name="android:windowIsTranslucent">true</item>` 后进入/退出 Activity 的动画失效
，在小米、华为的 6.0 上都出现这种情况，小米的 4.4 上则一切正常。

**Comment by yummyChina** [comment]
我也有这个问题，使用了透明主题之后会产生默认的activity动画，感觉是appcompat包的兼容性问题，尤其是使用了toolbar之后，试验成功的都是用DarkActionBar或者自定义标题的,毕竟不是原生支持的内容，很难 兼容，感觉强行加入滑动关闭功能的话，整个app框架的局限性 就很强

**Comment by tysheng** [comment]
你的Animation要继承Animation.Translucent

**Comment by iielse** [comment]
补充一下： 继承了 Translucent 后
Aactivity 打开 Bactivity  只有B的入场动画有效， a的离场动画无效
Bactivity 返回 Aactivity  只有B的离场动画有效， a的入场动画无效。

我现在无视那2个无效动画，感觉效果也是可以的。
