### ISSUE TITLE
求添加一个策划触发返回时的回调??

### ISSUE THREAD

**Issue by lobster002** [ikew0ng/SwipeBackLayout#127]
如题?

**Comment by ikew0ng** [comment]
参考 Demo 中下方的代码：onEdgeTouch

mSwipeBackLayout.addSwipeListener(new SwipeBackLayout.SwipeListener() {
            @Override
            public void onScrollStateChange(int state, float scrollPercent) {

            }

            @Override
            public void onEdgeTouch(int edgeFlag) {
                vibrate(VIBRATE_DURATION);
            }

            @Override
            public void onScrollOverThreshold() {
                vibrate(VIBRATE_DURATION);
            }
        });
