### ISSUE TITLE
滑动时有一定几率导致拉伸

### ISSUE THREAD

**Issue by yrom** [ikew0ng/SwipeBackLayout#13]
是webview的原因？？

![device-2013-09-25-004058](https://f.cloud.github.com/assets/2888674/1201642/22b91dd8-2538-11e3-84bc-e7cb36ac930e.png)

释放回去
![device-2013-09-25-004554](https://f.cloud.github.com/assets/2888674/1201678/ae98f24c-2538-11e3-8af6-337c9c08ba10.png)

上下稍微滑动后恢复正常
![device-2013-09-25-004413](https://f.cloud.github.com/assets/2888674/1201671/7228e0ec-2538-11e3-9cd6-2980ed4a3579.png)

**Comment by yjiang2009** [comment]
@yrom  @ikew0ng ,最后你这个滑动时拉伸的问题咋解决的啊老铁。
