### ISSUE TITLE
滑动时背景是黑色

### ISSUE THREAD

**Issue by ZhouBey** [ikew0ng/SwipeBackLayout#134]
滑动后退时，背景是黑色的，主题设置成透明色后正常了，但是会引发另一个问题，快速点击按钮去startActivity时，因为背景是透明的，会显示桌面，误点桌面图标

**Comment by xx394984678** [comment]
在你的style下添加这么一行代码
       <item name="android:windowIsTranslucent">true</item>

**Comment by curry-zhou** [comment]
请仔细阅读我的问题，我加过style,但是会引发另一个问题

**Comment by 18710891669** [comment]
最后解决了吗@ZhouBey

**Comment by H-Mo** [comment]
1.首先设置背景透明
`<item name="android:windowIsTranslucent">true</item>`
2.再给启动APP时的Activity单独设置不透明
`  
 <style name="AppThemeMain" parent="AppTheme">
        <item name="android:windowIsTranslucent">false</item>
 </style>
`
AndroidManifest.xml中单独设置不透明的背景风格
`
<activity android:name=".main.activity.MainActivity"
                  android:theme="@style/AppThemeMain"
                  android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
</activity>
`

**Comment by ikew0ng** [comment]
楼上正解。
