### ISSUE TITLE
向右滑出现黑屏

### ISSUE THREAD

**Issue by czn6** [ikew0ng/SwipeBackLayout#25]
首先，谢谢你的分享。
我是个新手，想做一个滑动退出的功能。
我把整个zip下载下来，但是却不知道怎么用。。。
后来我把要用到的Activity 资源等拿到了我的项目，终于运行了起来。
我从A（就一个Button）点击跳转到B ，再想从B返回到A ,发现滑动出来的是黑屏，不是A的界面。请问我这个问题应该怎么解决呢？ 
打扰了。

**Comment by loganguo** [comment]
@ikew0ng 可是指定了透明背景之后，默认的activity切换动画就失效了。如何启用默认的activity切换动画呢？谢谢。
