### ISSUE TITLE
android:windowAnimationStyle失效问题

### ISSUE THREAD

**Issue by dodola** [ikew0ng/SwipeBackLayout#3]
应用框架后会导致<item name="android:windowAnimationStyle">设置的动画失效

**Comment by ayyb1988** [comment]
@starklu   多谢。困扰的一个问题解决了

**Comment by ownwell** [comment]
Animation.Translucent 这个不好用啊

**Comment by ownwell** [comment]
能fix么

**Comment by ikew0ng** [comment]
sorry 节后我看看。

2015-09-28 19:11 GMT+08:00 CyningLee <notifications@github.com>:

**Comment by captain-miao** [comment]
@yrom 设置android:windowAnimationStyle 在4.4.2会在切换Activity 的时候也起作用.....求破//这个能解决吗？ 应该是view重建导致～

**Comment by captain-miao** [comment]
@richard1122 目前我的做法是最下面的Activity 设置成 windowIsTranslucent false， 这样就不会发生滑动时候下面的消失了。//可以～～ 赞

**Comment by evernightking** [comment]
研究了一下，设为透明activity会造成activity切换动画失效，只能设置window动画，这样搞的话就只有上层activity动画了，而且还会有一个bug，就是按下home键会造成闪屏，但是在代码中使用overridePendingTransition（）方法设置动画不会有闪屏的情况，但是下一层activity的动画就没有了，只有顶层activity有动画，推测微信是自己有一个栈去管理activity，设置动画。楼上右划底下内容不见的情况可以把avtivity中的view设置背景解决。Android就是个坑，还是ios开发爽啊……

**Comment by richard1122** [comment]
@evernightking 现在应该更推荐用 fragment 来做类似事情了。。应该会容易很多。

过了这么久我都忘了这个 issue 当时我给出 workaround 的背景了，没法给出任何建议了~
