### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by waysnotes** [ikew0ng/SwipeBackLayout#30]
06-09 14:38:53.874: E/AndroidRuntime(26777): FATAL EXCEPTION: main
06-09 14:38:53.874: E/AndroidRuntime(26777): java.lang.NullPointerException
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.GLES20RenderLayer.redrawLater(GLES20RenderLayer.java:114)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.View.getHardwareLayer(View.java:12562)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.View.getDisplayList(View.java:12809)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.View.getDisplayList(View.java:12890)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.View.draw(View.java:13640)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.View.getDisplayList(View.java:12841)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.View.getDisplayList(View.java:12890)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.ViewRootImpl.draw(ViewRootImpl.java:2567)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2236)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1211)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5039)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.Choreographer.doCallbacks(Choreographer.java:579)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.Choreographer.doFrame(Choreographer.java:548)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.os.Handler.handleCallback(Handler.java:800)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.os.Handler.dispatchMessage(Handler.java:100)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.os.Looper.loop(Looper.java:194)
06-09 14:38:53.874: E/AndroidRuntime(26777): at android.app.ActivityThread.main(ActivityThread.java:5433)
06-09 14:38:53.874: E/AndroidRuntime(26777): at java.lang.reflect.Method.invokeNative(Native Method)
06-09 14:38:53.874: E/AndroidRuntime(26777): at java.lang.reflect.Method.invoke(Method.java:525)
06-09 14:38:53.874: E/AndroidRuntime(26777): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
06-09 14:38:53.874: E/AndroidRuntime(26777): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
06-09 14:38:53.874: E/AndroidRuntime(26777): at dalvik.system.NativeStart.main(Native Method)
这个错误怎么解决？

**Comment by netxiaosheng** [comment]
知道怎么解决吗
