### ISSUE TITLE
On android 4.4.4 when swiping I see my phone's background

### ISSUE THREAD

**Issue by rootux** [ikew0ng/SwipeBackLayout#38]
Tried the version in the play store,
When I swipe instead of showing the old activity it shows my phone background / the task manager.
this happens on 4.4.4

**Comment by sharpwhisper** [comment]
在我的S3(4.0.4)，Nexus 4(4.4.4)，Nexus4(5.0)上swipeback在屏幕底端失效，要在上半部分滑动才能启动。这是为什么》
