### ISSUE TITLE
左滑返回时出现黑屏

### ISSUE THREAD

**Issue by codetalks-new** [ikew0ng/SwipeBackLayout#4]
RT:
具体描述：
（0）一个子Activity继承自SwipeBackActivity，没有作任何修改。
（1）在一个子Activity中从左边滑动想返回时，屏幕变黑。再按两次按物理返回键时
可以回到父Activity中（感觉进入了一个子Activity与父Activity的一个中间黑色界面）
（2）系统MIUI V5 3.8.16

**Comment by huimieni** [comment]
android 5.0以上全是黑屏

**Comment by 410133062** [comment]
这个问题怎么解决   什么时候能修复

**Comment by Hellozhongxin** [comment]
试了设置主题的方式，还是黑屏。  - -

**Comment by ibrucekong** [comment]
我的是白屏，但是设置之后，还是白屏

**Comment by KingOfSu** [comment]
这个能解决左滑关闭黑屏闪一下的问题,但是在华为最新系统那里,通过scheme打开本应用的时候,会导致屏幕Activity透明,其他应用不会
