### ISSUE TITLE
android 4.4.4侧滑退出显示app启动界面

### ISSUE THREAD

**Issue by lejun** [ikew0ng/SwipeBackLayout#45]
RT：
情况，我手机上两台手机：nexus5(4.4.4)与化为X6（4.4.2）退出滑动效果不一致。
两台手机都是运行同一套代码
1，nexus5 只有当activity完全退出时，前一个activity才出弹出
2，华为X6则可以完美展示（即在滑动退出时，就可以看见前一个activity）

（已经设置透明主题）
参考过这个问题：
https://github.com/Issacw0ng/SwipeBackLayout/issues/4

**Comment by fulianzhi** [comment]
我也碰到了同样的问题。。。
我的是Android 4.4.4（MX2）, 我只有一个activity， 一滑动就直接看到桌面了
