### ISSUE TITLE
设置滑动区域为全屏以后会影响ViewPager

### ISSUE THREAD

**Issue by MrFuFuFu** [ikew0ng/SwipeBackLayout#49]
@Issacw0ng 你好，看到 https://github.com/Issacw0ng/SwipeBackLayout/issues/8 。通过设置SwipeBackLayout 的setEdgeSize 我设置为我手机的宽度，同时设置了setEdgeTrackingEnabled 为EDGE_LEFT。这个时候右滑其实没有响应，然后我修改了ViewDragHelper 的getEdgeTouched 的返回值为 EDGE_LEFT。结果任意位置右滑是能响应关闭的。但是此时 Activity 中的 ViewPager 并没有响应，请问有什么解决办法吗？

**Comment by lixiao000018** [comment]
设置ViewPager的触摸事件 当触摸到ViewPager 不让父控件干扰

**Comment by MrFuFuFu** [comment]
@lixiao000018 谢谢~~~后来改成了从边缘滑动关闭了，没有影响了
