### ISSUE TITLE
请问手动滑动activity finish 是如何调用的？

### ISSUE THREAD

**Issue by ayyb1988** [ikew0ng/SwipeBackLayout#57]
在继承swipebackactivity的activity。需要setresult返回数据，但是没有追踪到滑动使activity finish的调用。
这个scrollToFinishActivity方法没有调用。不知道在哪finish的？

**Comment by ayyb1988** [comment]
sorry,已解决

**Comment by JitenNumberTank** [comment]
@ayyb1988  Do you provide code here so I can see how you resolve that issue. I got same issue. I can't get result back from front activity after finish
