### ISSUE TITLE
快速滑动关闭 出现空指针

### ISSUE THREAD

**Issue by jingjing0327** [ikew0ng/SwipeBackLayout#79]
07-27 15:33:32.015: E/AndroidRuntime(9325): java.lang.NullPointerException
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.view.View.getHardwareLayer(View.java:10215)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2947)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.view.View.getDisplayList(View.java:10452)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:856)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2089)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1787)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2642)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.os.Looper.loop(Looper.java:154)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at android.app.ActivityThread.main(ActivityThread.java:4624)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at java.lang.reflect.Method.invoke(Method.java:511)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
07-27 15:33:32.015: E/AndroidRuntime(9325): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by jingjing0327** [comment]
@ikew0ng 
Demo上面也有这个问题

**Comment by jingjing0327** [comment]
android 4.0.4 上面的问题

**Comment by jingjing0327** [comment]
android 4.3 上面没问题

**Comment by jingjing0327** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by jingjing0327** [comment]
真是见了鬼了

**Comment by jingjing0327** [comment]
@ikew0ng 
@ikew0ng 
@ikew0ng 
@ikew0ng

**Comment by jingjing0327** [comment]
@ikew0ng 
@ikew0ng 
@ikew0ng

**Comment by jingjing0327** [comment]
我的nexus 6 ，5.1 没有问题

**Comment by jingjing0327** [comment]
是滑动过快造成的

**Comment by ikew0ng** [comment]
cool...  我研究研究，你去掉 setLayerType 试试。
