### ISSUE TITLE
关于增大划动区域的问题

### ISSUE THREAD

**Issue by terryyhl** [ikew0ng/SwipeBackLayout#8]
你好，使用了你的划动返回，但只有很小的区域有效。能否让其支持全屏，或者 半屏，就像你的fubbo一样，我设置了全屏但会与其他列表冲突。

**Comment by herohd** [comment]
为何在滑动返回上一层不是显示activity的View，而是直接显示桌面

**Comment by 79144876** [comment]
包括activity里面有listview/viewpager/webview 的时候 如果设置的滑动区域比较大比如屏幕的1/2 左手滑动屏幕,会和本身的上下滑动冲突，直接会返回，但其实用户是希望上下滑动的，而非滑动返回。

**Comment by lyl873825813** [comment]
Activity中有WebView时，继承了SwipeBackActivity后WebView的内容就不能上下滑动了，这个该怎么解决？

**Comment by granden** [comment]
同样是调用 setEdgeSize(),只要调用此方法赋值进去了滑动返回的效果就失效,请问要怎么解决?

**Comment by qindachang** [comment]
http://blog.csdn.net/u013003052/article/details/50448617  这是我的解决办法，希望对大家有用

**Comment by helengray** [comment]
这是我的解决方法：
1、修改SwipeBackLayout.EDGE_ALL
`EDGE_ALL=ViewDragHelper.EDGE_ALL`

2、修改ViewDragHelper$getEdgeTouched

`private int getEdgeTouched(int x, int y) {
        int result = 0;
        if(mTrackingEdges == EDGE_ALL) {
            if (x < mParentView.getLeft() + mEdgeSize)
                result = EDGE_LEFT;
            if (y < mParentView.getTop() + mEdgeSize)
                result = EDGE_TOP;
            if (x > mParentView.getRight() - mEdgeSize)
                result = EDGE_RIGHT;
            if (y > mParentView.getBottom() - mEdgeSize)
                result = EDGE_BOTTOM;
        }else {
            result = mTrackingEdges;
        }
        return result;
    }`

**Comment by chenglei1986** [comment]
我觉得这个改下应该好使

```java
private int getEdgeTouched(int x, int y) {
    int result = 0;

    if (x < mParentView.getLeft() + mEdgeSize && (mTrackingEdges & EDGE_LEFT) != 0)
        result |= EDGE_LEFT;
    if (y < mParentView.getTop() + mEdgeSize && (mTrackingEdges & EDGE_TOP) != 0)
        result |= EDGE_TOP;
    if (x > mParentView.getRight() - mEdgeSize && (mTrackingEdges & EDGE_RIGHT) != 0)
        result |= EDGE_RIGHT;
    if (y > mParentView.getBottom() - mEdgeSize && (mTrackingEdges & EDGE_BOTTOM) != 0)
        result |= EDGE_BOTTOM;

    return result;
}
```

**Comment by DaveBoy** [comment]
就是getEdgeTouched这个方法的判断出问题了，mEdgeSize建议改成四个参数分为上下左右，你这样统一了结果判断就出问题了。
